# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Approve"

on:
  - "pull_request"

jobs:
  approve:
    name: "Approve"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Approve"
        uses: "hmarr/auto-approve-action@v2.0.0"
        if: "(github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]') && startsWith(github.event.pull_request.title, 'Build(deps-dev)')"
        with:
          github-token: "${{ secrets.AUTO_APPROVE_TOKEN }}"
