# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "**"

name: "Continuous Integration"

jobs:
  coding-standards:
    name: "Coding Standards"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.2

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1.1.0

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@master
        with:
          coverage: none
          extension-csv: "mbstring"
          php-version: ${{ matrix.php-version }}

      - name: "Validate composer.json and composer.lock"
        run: $(which composer) validate --strict

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1.0.2
        with:
          path: ~/.composer/cache
          key: php${{ matrix.php-version }}-composer-locked-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php${{ matrix.php-version }}-composer-locked-

      - name: "Install locked dependencies with composer"
        run: $(which composer) install --no-interaction --no-progress --no-suggest

      - name: "Run localheinz/composer-normalize"
        run: $(which composer) normalize --dry-run

      - name: "Create cache directory for friendsofphp/php-cs-fixer"
        run: mkdir -p .build/php-cs-fixer

      - name: "Cache cache directory for friendsofphp/php-cs-fixer"
        uses: actions/cache@v1.0.2
        with:
          path: ~/.build/php-cs-fixer
          key: php${{ matrix.php-version }}-php-cs-fixer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php${{ matrix.php-version }}-php-cs-fixer-

      - name: "Run friendsofphp/php-cs-fixer"
        run: vendor/bin/php-cs-fixer fix --config=.php_cs --diff --diff-format=udiff --dry-run --verbose

  dependency-analysis:
    name: "Dependency Analysis"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.4

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1.1.0

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@master
        with:
          coverage: none
          extension-csv: "mbstring"
          php-version: ${{ matrix.php-version }}

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1.0.2
        with:
          path: ~/.composer/cache
          key: php${{ matrix.php-version }}-composer-locked-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php${{ matrix.php-version }}-composer-locked-

      - name: "Install locked dependencies with composer"
        run: $(which composer) install --no-interaction --no-progress --no-suggest

      - name: "Run maglnet/composer-require-checker"
        uses: docker://localheinz/composer-require-checker-action:1.1.0

  static-code-analysis:
    name: "Static Code Analysis"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.4

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1.1.0

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@master
        with:
          coverage: none
          extension-csv: "mbstring"
          php-version: ${{ matrix.php-version }}

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1.0.2
        with:
          path: ~/.composer/cache
          key: ${{ matrix.php-version }}-composer-locked-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ matrix.php-version }}-composer-locked-

      - name: "Install locked dependencies with composer"
        run: $(which composer) install --no-interaction --no-progress --no-suggest

      - name: "Run phpstan/phpstan"
        run: vendor/bin/phpstan analyse --configuration=phpstan.neon

  test-dependencies-installable-lowest-supported-php-version:
    name: "Test dependencies installable on lowest supported PHP version"

    runs-on: ubuntu-latest

    container:
      image: php:7.2.0-cli-alpine

    steps:
      - name: "Install Composer"
        run: |
          EXPECTED_SIGNATURE="$(curl -L https://composer.github.io/installer.sig)"
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

          if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
          then
              >&2 echo 'ERROR: Invalid installer signature'
              rm composer-setup.php
              exit 1
          fi

          php composer-setup.php --quiet --install-dir=/usr/local/bin --filename=composer
          RESULT=$?
          rm composer-setup.php
          exit $RESULT

      - name: "Checkout"
        uses: actions/checkout@v1.1.0

      - name: "Dry update dependencies with Composer"
        run: composer update --dry-run --no-interaction --no-progress --no-suggest

  tests:
    name: "Tests"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.2
          - 7.3
          - 7.4

        dependencies:
          - lowest
          - locked
          - highest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1.1.0

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@master
        with:
          coverage: none
          extension-csv: "mbstring"
          php-version: ${{ matrix.php-version }}

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1.0.2
        with:
          path: ~/.composer/cache
          key: php${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-

      - name: "Install lowest dependencies with composer"
        if: matrix.dependencies == 'lowest'
        run: $(which composer) update --no-interaction --no-progress --no-suggest --prefer-lowest

      - name: "Install locked dependencies with composer"
        if: matrix.dependencies == 'locked'
        run: $(which composer) install --no-interaction --no-progress --no-suggest

      - name: "Install highest dependencies with composer"
        if: matrix.dependencies == 'highest'
        run: $(which composer) update --no-interaction --no-progress --no-suggest

      - name: "Run auto-review tests with phpunit/phpunit"
        run: vendor/bin/phpunit --configuration=test/AutoReview/phpunit.xml

      - name: "Run unit tests with phpunit/phpunit"
        run: vendor/bin/phpunit --configuration=test/Unit/phpunit.xml

      - name: "Run integration tests with phpunit/phpunit"
        run: vendor/bin/phpunit --configuration=test/Integration/phpunit.xml

  code-coverage:
    name: "Code Coverage"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.4

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1.1.0

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@master
        with:
          coverage: xdebug
          extension-csv: "mbstring"
          php-version: ${{ matrix.php-version }}

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1.0.2
        with:
          path: ~/.composer/cache
          key: php${{ matrix.php-version }}-composer-locked-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php${{ matrix.php-version }}-composer-locked-

      - name: "Install locked dependencies with composer"
        run: $(which composer) install --no-interaction --no-progress --no-suggest

      - name: "Dump Xdebug filter with phpunit/phpunit"
        run: vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --dump-xdebug-filter=.build/phpunit/xdebug-filter.php

      - name: "Collect code coverage with Xdebug and phpunit/phpunit"
        run: vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --coverage-clover=build/logs/clover.xml --prepend=.build/phpunit/xdebug-filter.php

      - name: "Send code coverage report to Codecov.io"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)

  mutation-tests:
    name: "Mutation Tests"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.4

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1.1.0

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@master
        with:
          coverage: xdebug
          extension-csv: "mbstring"
          php-version: ${{ matrix.php-version }}

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1.0.2
        with:
          path: ~/.composer/cache
          key: php${{ matrix.php-version }}-composer-locked-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php${{ matrix.php-version }}-composer-locked-

      - name: "Install locked dependencies with composer"
        run: $(which composer) install --no-interaction --no-progress --no-suggest

      - name: "Run mutation tests with infection/infection"
        run: vendor/bin/infection --ignore-msi-with-no-mutations --min-covered-msi=100 --min-msi=100
